_wandb:
    value:
        cli_version: 0.21.1
        e:
            p63yvvs8pe3b9nhloi7nsntmqiaixdhg:
                args:
                    - --model_family
                    - llava
                    - --task_suite_name
                    - libero_90
                    - --center_crop
                    - "False"
                    - --use_wandb
                    - "True"
                    - --wandb_project
                    - ecot_libero
                    - --wandb_entity
                    - AGI_CSI
                codePath: experiments/robot/libero/run_libero_eval.py
                codePathLocal: experiments/robot/libero/run_libero_eval.py
                cpu_count: 56
                cpu_count_logical: 48
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "935062740992"
                        used: "647261442048"
                email: gnih1226@gmail.com
                executable: /home/work/AGI_NIH/anaconda3/envs/openvla/bin/python
                git:
                    commit: 1813ad76001f1e08095088f94a86c43fc0e457a3
                    remote: https://github.com/MichalZawalski/embodied-CoT.git
                gpu: NVIDIA H100 80GB HBM3
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-f2ff4815-68e7-955a-5166-d91399cef176
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-ca1bdbf3-6aaa-2fd6-a5c5-fc2887f85a17
                host: main1
                memory:
                    total: "513248591872"
                os: Linux-5.15.0-130-generic-x86_64-with-glibc2.35
                program: /home/work/AGI_NIH/embodied-CoT/experiments/robot/libero/run_libero_eval.py
                python: CPython 3.10.18
                root: /home/work/AGI_NIH/embodied-CoT
                startedAt: "2025-08-11T12:00:25.491554Z"
                writerId: p63yvvs8pe3b9nhloi7nsntmqiaixdhg
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 2
                - 3
                - 11
                - 41
                - 49
                - 63
                - 71
            "2":
                - 1
                - 2
                - 3
                - 11
                - 41
                - 49
                - 63
                - 71
            "3":
                - 13
            "4": 3.10.18
            "5": 0.21.1
            "6": 4.40.1
            "12": 0.21.1
            "13": linux-x86_64
