_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 2
                - 3
                - 11
                - 41
                - 49
                - 55
                - 63
                - 71
                - 98
            "2":
                - 1
                - 2
                - 3
                - 11
                - 41
                - 49
                - 55
                - 63
                - 71
                - 98
            "3":
                - 13
                - 23
                - 55
            "4": 3.8.20
            "5": 0.19.11
            "6": 4.40.1
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
